site_name: 领航国际教育 - BA专业自学系列课程
site_description: 领航国际教育 - BA专业自学系列课程
site_url: https://navigationba.github.io/NavigationBA_Basics/
site_dir: site
edit_uri: edit/main/docs/
repo_url: https://github.com/NavigationBA/NavigationBA_Basics_Code 
repo_name: GitHub

theme:
  name: material
  language: zh
  features:
    - navigation.tabs        # 顶部导航标签
    - navigation.sections    # 子导航分组
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: blue   # 主色（导航栏背景）
      accent: blue    # 强调色（按钮、链接高亮）
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换到日间模式

markdown_extensions:
  - admonition
  - md_in_html
  - toc:
      permalink: true
      title: 本章目录
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
      include_requirejs: false
      kernel_name: python311

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:

  - 首页:
    - ✴️ 欢迎页面: index.md
    - ✴️ 课程介绍: index/index1.md
    - ✴️ 课程大纲: index/index2.md

  - Module 1 - Python 基础: 
    - 课程介绍:                    
      - ✴️ 课程简介:                                            Module1/Topic00/Topic00_01/Topic00_01.md
      - ✴️ 课程大纲:                                            Module1/Topic00/Topic00_02/Topic00_02.md
    - Topic 1 - Python 基本介绍:
      - ✴️ Topic 1 章节概览:                                    Module1/Topic01/Topic01_00/Topic01_00.md
      - ✅ Topic 1.1 - Python 语言简介:                          Module1/Topic01/Topic01_01/Topic01_01.md
      - ✅ Topic 1.2 - Python 与 PyCharm 安装:                  Module1/Topic01/Topic01_02/Topic01_02.md
      - ✅ Topic 1.3 - Python 学习技巧:                          Module1/Topic01/Topic01_03/Topic01_03.md
      - ☑️ Topic 1.4 - 其他运行 Python 的方式（补充）:            Module1/Topic01/Topic01_04/Topic01_04.md
    - Topic 2 - Python 编程核心:
      - ✴️ Topic 2 章节概览:                                     Module1/Topic02/Topic02_00/Topic02_00.md
      - ✅ Topic 2.1 - 一些简单的 Python 程序:                    Module1/Topic02/Topic02_01/Topic02_01.md
      - ✅ Topic 2.2 - 变量与赋值:                               Module1/Topic02/Topic02_02/Topic02_02.md
      - ✅ Topic 2.3 - 注释:                                    Module1/Topic02/Topic02_03/Topic02_03.md
      - ✅ Topic 2.4 - 用户输入 - input() 函数:                  Module1/Topic02/Topic02_04/Topic02_04.md
      - ✅ Topic 2.5 - print() 函数拓展功能:                     Module1/Topic02/Topic02_05/Topic02_05.md
      - ☑️ Topic 2.6 - Python 代码规范（补充）:                   Module1/Topic02/Topic02_06/Topic02_06.md
    - Topic 3 - Python 基础数据类型之数字:
      - ✴️ Topic 3 章节概览:                                    Module1/Topic03/Topic03_00/Topic03_00.md
      - ✅ Topic 3.1 - 数字类型之整数与浮点数:                     Module1/Topic03/Topic03_01/Topic03_01.md
      - ✅ Topic 3.2 - 数字类型之布尔型:                          Module1/Topic03/Topic03_02/Topic03_02.md
      - ✅ Topic 3.3 - 数字类型之空值:                           Module1/Topic03/Topic03_03/Topic03_03.md
      - ☑️ Topic 3.4 - 数字类型之复数（补充）:                     Module1/Topic03/Topic03_04/Topic03_04.md
    - Topic 4 - Python 基础数据类型之字符串:
      - ✴️ Topic 4 章节概览:                                    Module1/Topic04/Topic04_00/Topic04_00.md
      - ✅ Topic 4.1 - 字符串的基本概念:                         Module1/Topic04/Topic04_01/Topic04_01.md
      - ✅ Topic 4.2 - 字符串的索引与切片:                        Module1/Topic04/Topic04_02/Topic04_02.md
      - ✅ Topic 4.3 - 字符串的常见操作:                          Module1/Topic04/Topic04_03/Topic04_03.md
      - ✅ Topic 4.4 - 格式化字符串:                             Module1/Topic04/Topic04_04/Topic04_04.md
    - Topic 5 - Python 组合数据类型:
      - ✴️ Topic 5 章节概览:                                     Module1/Topic05/Topic05_00/Topic05_00.md
      - ✅ Topic 5.1 - Python 组合数据类型之列表:                  Module1/Topic05/Topic05_01/Topic05_01.md
      - ✅ Topic 5.2 - Python 组合数据类型之元组:                  Module1/Topic05/Topic05_02/Topic05_02.md
      - ✅ Topic 5.3 - Python 组合数据类型之集合:                  Module1/Topic05/Topic05_03/Topic05_03.md
      - ✅ Topic 5.4 - Python 组合数据类型之字典:                  Module1/Topic05/Topic05_04/Topic05_04.md
      - ✅ Topic 5.5 - Python 组合数据类型之间的转换:               Module1/Topic05/Topic05_05/Topic05_05.md
    - Topic 6 - 条件语句 - if 语句:
      - ✴️ Topic 6 章节概览:                                    Module1/Topic06/Topic06_00/Topic06_00.md
      - ✅ Topic 6.1 - 条件语句的基本用法:                        Module1/Topic06/Topic06_01/Topic06_01.md
      - ✅ Topic 6.2 - 条件语句的进阶用法:                        Module1/Topic06/Topic06_02/Topic06_02.md
    - Topic 7 - 循环语句 - while 循环:
      - ✴️ Topic 7 章节概览:                                     Module1/Topic07/Topic07_00/Topic07_00.md
      - ✅ Topic 7.1 - while 循环的基本用法:                      Module1/Topic07/Topic07_01/Topic07_01.md
      - ✅ Topic 7.2 - while 循环的进阶用法:                      Module1/Topic07/Topic07_02/Topic07_02.md
      - ✅ Topic 7.3 - while 无限循环的程序设计:                   Module1/Topic07/Topic07_03/Topic07_03.md
    - Topic 8 - 循环语句 - for 循环:
      - ✴️ Topic 8 章节概览:                                    Module1/Topic08/Topic08_00/Topic08_00.md
      - ✅ Topic 8.1 - for 循环的基本用法:                       Module1/Topic08/Topic08_01/Topic08_01.md
      - ✅ Topic 8.2 - for 循环的进阶用法:                       Module1/Topic08/Topic08_02/Topic08_02.md
      - ☑️ Topic 8.3 - for 循环的高级用法（补充）:                Module1/Topic08/Topic08_03/Topic08_03.md
    - Topic 9 - 自定义函数:
      - ✴️ Topic 9 章节概览:                                    Module1/Topic09/Topic09_00/Topic09_00.md
      - ✅ Topic 9.1 - 函数的基本用法:                           Module1/Topic09/Topic09_01/Topic09_01.md
      - ✅ Topic 9.2 - 函数的进阶用法:                           Module1/Topic09/Topic09_02/Topic09_02.md
      - ☑️ Topic 9.3 - 函数的高级用法（补充）:                    Module1/Topic09/Topic09_03/Topic09_03.md
      - ☑️ Topic 9.4 - 函数拓展（补充）:                         Module1/Topic09/Topic09_04/Topic09_04.md
    - Topic 10 - 异常处理:
      - ✴️ Topic 10 章节概览:                                  Module1/Topic10/Topic10_00/Topic10_00.md
      - ✅ Topic 10.1 - 异常处理的基本用法:                      Module1/Topic10/Topic10_01/Topic10_01.md
      - ✅ Topic 10.2 - 异常处理的高级用法:                      Module1/Topic10/Topic10_02/Topic10_02.md
      - ☑️ Topic 10.3 - 异常处理拓展（补充）:                     Module1/Topic10/Topic10_03/Topic10_03.md
    - Topic 11 - 文件操作:
      - ✴️ Topic 11 章节概览:                                  Module1/Topic11/Topic11_00/Topic11_00.md
      - ✅ Topic 11.1 - 文件操作的基本用法:                      Module1/Topic11/Topic11_01/Topic11_01.md
      - ✅ Topic 11.2 - 使用 with 语句进行文件读写:              Module1/Topic11/Topic11_02/Topic11_02.md
      - ☑️ Topic 11.3 - 认识其他的文件类型（补充）:               Module1/Topic11/Topic11_03/Topic11_03.md
    - Topic 12 - 模块与包:
      - ✴️ Topic 12 章节概览:                                  Module1/Topic12/Topic12_00/Topic12_00.md
      - ✅ Topic 12.1 - 模块与包的引用:                         Module1/Topic12/Topic12_01/Topic12_01.md
      - ✅ Topic 12.2 - 自定义模块与包:                         Module1/Topic12/Topic12_02/Topic12_02.md
      - ☑️ Topic 12.3 - 自定义模块与包的高级技巧（补充）:          Module1/Topic12/Topic12_03/Topic12_03.md
      - ☑️ Topic 12.4 - 常用的内置模块与包（补充）:               Module1/Topic12/Topic12_04/Topic12_04.md
      - ☑️ Topic 12.5 - 常用的第三方模块与包（补充）:             Module1/Topic12/Topic12_05/Topic12_05.md
    - Topic 13 - Python 程序开发（补充）:
      - ✴️ Topic 13 章节概览:                                  Module1/Topic13/Topic13_00/Topic13_00.md
      - ☑️ Topic 13.1 - Python 程序开发概览:                    Module1/Topic13/Topic13_01/Topic13_01.md
      - ☑️ Topic 13.2 - Python 程序开发演示 - 动物园程序开发:     Module1/Topic13/Topic13_02/Topic13_02.md
      - ☑️ Topic 13.3 - Python 程序开发演示 - 动物园程序改进:     Module1/Topic13/Topic13_03/Topic13_03.md
    - Topic 14 - 金融计算器项目 - Python 基础结课项目（补充）:
      - ✴️ Topic 14 章节概览:                                  Module1/Topic14/Topic14_00/Topic14_00.md
      - ☑️ Topic 14.1 - 项目背景介绍与主程序框架搭建:              Module1/Topic14/Topic14_01/Topic14_01.md
      - ☑️ Topic 14.2 - 表达式计算功能:                          Module1/Topic14/Topic14_02/Topic14_02.md
      - ☑️ Topic 14.3 - 现金流计算功能:                          Module1/Topic14/Topic14_03/Topic14_03.md
      - ☑️ Topic 14.4 - 金钱时间价值功能:                        Module1/Topic14/Topic14_04/Topic14_04.md
      - ☑️ Topic 14.5 - 完善主程序与后续工作:                     Module1/Topic14/Topic14_05/Topic14_05.md
      - ☑️ Topic 14.6 - 金融计算器程序升级 - 版本 v2:             Module1/Topic14/Topic14_06/Topic14_06.md
      - ☑️ Topic 14.7 - 金融计算器程序升级 - 版本 v3:             Module1/Topic14/Topic14_07/Topic14_07.md

  - Module 2 - Python 面向对象:
    - 课程介绍:                    
      - ✴️ 课程简介:                                            Module2/Topic00/Topic00_01/Topic00_01.md
      - ✴️ 课程大纲:                                            Module2/Topic00/Topic00_02/Topic00_02.md
    - Topic 1 - Python 面向对象基础:
      - ✴️ Topic 1 章节概览:                                    Module2/Topic01/Topic01_00/Topic01_00.md
      - ✅ Topic 1.1 - 面向对象编程简介:                         Module2/Topic01/Topic01_01/Topic01_01.md
      - ✅ Topic 1.2 - 类和对象的基本概念:                       Module2/Topic01/Topic01_02/Topic01_02.md
      - ✅ Topic 1.3 - 类的继承与多态:                           Module2/Topic01/Topic01_03/Topic01_03.md
    - Topic 2 - Python 面向对象进阶（补充）:
      - ✴️ Topic 2 章节概览:                                    Module2/Topic02/Topic02_00/Topic02_00.md
      - ☑️ Topic 2.1 - 类与类之间的关联与组合关系:                 Module2/Topic02/Topic02_01/Topic02_01.md
      - ☑️ Topic 2.2 - 类继承的进阶用法:                         Module2/Topic02/Topic02_02/Topic02_02.md
      - ☑️ Topic 2.3 - 类对象:                                 Module2/Topic02/Topic02_03/Topic02_03.md
      - ☑️ Topic 2.4 - 单例:                                   Module2/Topic02/Topic02_04/Topic02_04.md
    - Topic 3 - Python 面向对象的程序开发方式（补充）:
      - ✴️ Topic 3 章节概览:                                    Module2/Topic03/Topic03_00/Topic03_00.md
      - ☑️ Topic 3.1 - Python 面向对象的程序开发概览:             Module2/Topic03/Topic03_01/Topic03_01.md
      - ☑️ Topic 3.2 - Python 面向对象程序 - 石头剪刀布程序开发:   Module2/Topic03/Topic03_02/Topic03_02.md
      - ☑️ Topic 3.3 - Python 面向对象程序 - 石头剪刀布程序改进:   Module2/Topic03/Topic03_03/Topic03_03.md
    - Topic 4 - 勇士与地下城项目 - Python 面向对象结课项目（补充）:
      - ✴️ Topic 4 章节概览:                                   Module2/Topic04/Topic04_00/Topic04_00.md
      - ☑️ Topic 4.1 - 游戏项目介绍:                            Module2/Topic04/Topic04_01/Topic04_01.md
      - ☑️ Topic 4.2 - 角色类与道具类的设计与实现:                Module2/Topic04/Topic04_02/Topic04_02.md
      - ☑️ Topic 4.3 - 地图类的设计与实现:                       Module2/Topic04/Topic04_03/Topic04_03.md
      - ☑️ Topic 4.4 - 整合各个游戏功能到主程序:                 Module2/Topic04/Topic04_04/Topic04_04.md
      - ☑️ Topic 4.5 - 游戏改进与扩展 - 升级 v2 版本:            Module2/Topic04/Topic04_05/Topic04_05.md
      - ☑️ Topic 4.6 - 游戏改进与扩展 - 升级 v3 版本:            Module2/Topic04/Topic04_06/Topic04_06.md
  
  - Module 3 - Python 数据分析:
    - 课程介绍:
      - ✴️ 课程简介:                                            Module3/Topic00/Topic00_01/Topic00_01.md
      - ✴️ 课程大纲:                                            Module3/Topic00/Topic00_02/Topic00_02.md
    - Topic 1 - Python 数据分析环境搭建:
      - ✴️ Topic 1 章节概览:                                    Module3/Topic01/Topic01_00/Topic01_00.md
      - ✅ Topic 1.1 - 下载 Anaconda 并创建 Conda 环境:          Module3/Topic01/Topic01_01/Topic01_01.md
      - ☑️ Topic 1.2 - Anaconda 中的其他功能（补充）:             Module3/Topic01/Topic01_02/Topic01_02.md
      - ☑️ Topic 1.3 - 使用命令行管理 Conda 环境（补充）:          Module3/Topic01/Topic01_03/Topic01_03.md
